apiVersion: apps/v1
kind: Deployment

metadata:
  name: franken-php
  labels:
    app: franken-php

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: franken-php

  template:
    metadata:
      labels:
        app: franken-php

    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}

      containers:
        - name: franken-php
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
